### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by mynam3isg00d** [Tommimon/advent-of-code-2021#1]
It seems like the leaderboard website is still not up, also there are many errors in the "Action" tab. Can you please work harder on those? Thank you.

**Comment by Tommimon** [comment]
Thanks for the report I will contact the mantainer of the web page and ask him to hurry up.

**Comment by riccardo-negri** [comment]
Hi mynam3isg00d, we're working full time on this issue trying to deploy the website as soon as possible. Thanks for your interest in this project.
